sudo: false
language: scala
scala:
- 2.11.8
# node_js:
# - 7.4.0
install:
# - sudo apt-get update
# - sudo apt-get install nodejs
# - sudo apt-get install npm

  #conflito de node:
  # - . $HOME/.nvm/nvm.sh
  # - nvm install stable
  # - nvm use stable
  # - npm install
# - . $HOME/.nvm/nvm.sh
# - nvm install node 7.4.0
# - nvm use node 7.4.0

notifications:
  email: false
before_install:
- npm install -g bower@1.8.0
- npm install -g gulp@3.9.1
- bower install
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
before_deploy:
# - sudo npm cache clean -f
# - sudo npm install -g n
# - sudo n stable
- gulp
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: cK8Cgc/JWZY8FyhBXwyQKum2ckl2eMIT/xHHlC7IixvgJBX6fARBJNy44x0IXUZYset4JYenobiVVB3ISIv3gTqBN1BEHit0PqWslT38q2bMV31yjiejV4PQDY8ZYI7fgHUYOK74leWPa46sfc2YR5QH5wt9yHHPfatdC5hCyBqRiI7fmmN95i6OEMFgp/AeheX6KTl5xX2GNzDXA9E/x7MYxXFnSc51gnBE4dqHddIC2GUB/MHXh8l4e/woQVkVm6sbLDYS58YSK/LfOgsjxD1pafiydfCmcjdoqu0Lu1kcZnjC8AzjYMFIY/gUkPJcRpjyTR+ZHydGgditHbpf5VRpJxPSG3hZ4I8wHuI9xwFwAunvL2L1xkC2q0hSSWsnkUz/ri3vqdXo/u1YCnb1DoVvdIgYymR9XzD7EuhkwbI1Ns1AvPpwekB7iPXPiVI+ir/9dhCzmFjNQmJJt3ErmBGuDs6OacwwH4xiNE18bs+oqFliRfC13rhvN5T/Rm7gIWQkNhhH6nQzGIwaX+moBHgnc4y+Na6DKz0DHJ13bXTPgQuCRAFgXPidLvjkd6kkCTyI2jW8E/stzLT9oIjc33RIGtK9aHvIV4UmAipUCjm5Zjn4U3UQRhqX+5ib7LPO8WlbRiXIo7dQ9LqIHj/PCHZI0qNZj5Ri4++dKao/9n4=
  app: meecarros
  skip_cleanup: true
