language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
node_js:
- 7.4.0
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
# deploy:
#   provider: heroku
#   api_key:
#     secure: wESHmrR/RQ/PncdFe3oPjsDpCIDyY3V0FIotQgG8u9CabKo46CMzqScgCToYean5u/+EV93Cvkg0mn+sFsnMGQftMOO0nzZB/4GtMwewfU5lgr28/DwWAnACPLeWZxax88/q4w4HDVMBv6CLg5kx1Doe5KVnCp5EspWVT0+sAipZFOcUqwOEJ1XwaOJxVrepAsK72DfsBK/0FMFvnfKAHsjLV1P73aQPb8TUe7cqXiBuhDl0AMhctC6IsK9IxsS3m0I6PeLU+OMc5J0kshIJI3YOUEqM1hfz/2hN5HYydffOBVfCKsxmVOn1hkRwEpCCJ1yA6Mhn+nmjHx7DzqCp2/vgW1AS3zEynvYAbhEEVVaYC+/u9GMZpDK74VGNvcQiJotujyWx3eUeJ7M9tRbzKXVHRju8R4AKJtZORpM8bqoRID4vigKL8KI6jZpoZBujWHExczsIbwNKYbc6+EW47sRY//U7VGuZXz4PqeVP/Dapz0hBAWUuTMmS9x73yrcMEvbg1Tno+KxE3BEgWRL2xdlnxOUcX0auCNqClhI1X22POIqLaG/7jIMF2bBN+UxtKSn4Q/5l0W5Ar6/7lsoezZlu+aAR9oVQVwMsblKxw0Mt/BugcK5rWIrJ/g7UhggBa8O/d64+hE6y/2uX7hrlILdcVvZa7twZomMadshMAqo=
#   app: meecarros
#   on:
#     repo: dhiegohenrique/meecarros
